name: bread_app
description: Bread delivery application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  ###
  flutter_svg: ^2.0.9

  # State Management
  flutter_bloc: ^9.1.1

  # Navigation
  go_router: ^17.0.1

  # Storage
  shared_preferences: ^2.5.4

  # HTTP
  dio: ^5.9.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.2

  smooth_page_indicator: ^2.0.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: w400
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: w500
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
